[tool.poetry]
name = "hwinarion"
version = "0.1.0"
description = "Control your computer with a microphone and webcam"
authors = ["Michael Lipschultz <michael.lipschultz@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
vosk = "^0.3.43"
pydub = "^0.25.1"
PyAudio = "^0.2.12"
matplotlib = "^3.6.0"
pocketsphinx = "^0.1.15"
numpy = "^1.23.3"
stt = "^1.4.0"
loguru = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
black = "^22.8.0"
pylint = "^2.15.3"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.pylint.'MESSAGES CONTROL']
disable = ["import-error"]

[tool.pylint.FORMAT]
max-line-length = 120
