name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]  #, "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Ubuntu Dependencies
        run: |
          sudo apt-get update
          sudo apt install -y \
            xauth xvfb \                                     # for run_without_display.py (xvfb might not be needed)
            tesseract-ocr \                                  # for bree
            ffmpeg \                                         # for openai-whisper and pydub
            libavcodec-extra libasound-dev portaudio19-dev \ # for pydub
            python3-tk                                       # for pyautogui (MouseInfo) in Linux

      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install

      - name: Test with pytest
        run: |
          poetry run python tests/run_without_display.py

      - name: Pre-Commit Checks
        run:
          poetry run pre-commit run --all-files
